export { default as Keyboard } from "components/Keyboard"
export { default as WordContent } from "components/WordContent"
export { default as Score } from "components/Score"
export { default as Timer } from "components/Timer"
export { default as Modal } from "components/Modal"
